site_name: Bulk

google_analytics: ['UA-59249373-1', 'http://codu.in/bulk/docs']
repo_name: jwbuurlage/bulk
repo_url: https://github.com/jwbuurlage/Bulk
copyright: "Bulk is licensed under the <a href='https://github.com/jwbuurlage/bulk/blob/master/LICENSE.md'>MIT license</a>"

theme: 'material'

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - codehilite
    - toc
    - footnotes
    - pymdownx.arithmatex

extra_javascript:
      - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

docs_dir: pages

nav:
- Home: 'index.md'
- Getting started: 'getting_started.md'
- Tour: 'tour.md'
- Introduction to Bulk:
    - Environment and world: 'environment_world.md'
    - Distributed variables: 'variables.md'
    - Coarrays: 'coarrays.md'
    - Message passing: 'message_passing.md'
- Case studies:
  - Parallel Scientific Computing: 'psc.md'
- API:
    - 'Index': 'api/index.md'
    - Classes:
        - 'environment': 'api/environment.md'
        - 'world': 'api/world.md'
        - 'var': 'api/var.md'
        - 'future': 'api/future.md'
        - 'coarray': 'api/coarray.md'
        - 'queue': 'api/queue.md'
        - 'timer': 'api/timer.md'
        - 'partitioning': 'api/partitioning.md'
    - Functions:
        - 'foldl': 'api/foldl.md'
        - 'gather_all': 'api/gather_all.md'
        - 'flatten': 'api/flatten.md'
        - 'unflatten': 'api/unflatten.md'
    - Nested classes:
        - 'var::image': 'api/var/image.md'
        - 'coarray::image': 'api/coarray/image.md'
        - 'coarray::writer': 'api/coarray/writer.md'
        - 'coarray::slice': 'api/coarray/slice.md'
        - 'coarray::slice_writer': 'api/coarray/slice_writer.md'
        - 'queue::sender': 'api/queue/sender.md'
    - Member functions:
        - 'environment::spawn': 'api/environment/spawn.md'
        - 'environment::available_processors': 'api/environment/available_processors.md'
        - 'world::rank': 'api/world/rank.md'
        - 'world::active_processors': 'api/world/active_processors.md'
        - 'world::next_rank': 'api/world/next_rank.md'
        - 'world::prev_rank': 'api/world/prev_rank.md'
        - 'world::sync': 'api/world/sync.md'
        - 'world::log': 'api/world/log.md'
        - 'world::log_once': 'api/world/log_once.md'
        - 'world::barrier': 'api/world/barrier.md'
        - 'var::constructor': 'api/var/constructor.md'
        - 'var::deconstructor': 'api/var/deconstructor.md'
        - 'var::operator=': 'api/var/assignment_operator.md'
        - 'var::value': 'api/var/value.md'
        - 'var::operator T': 'api/var/T_operator.md'
        - 'var::operator()': 'api/var/paren_operator.md'
        - 'var::broadcast': 'api/var/broadcast.md'
        - 'var::world': 'api/var/world.md'
        - 'var::image::operator=': 'api/var/image/assignment_operator.md'
        - 'var::image::get': 'api/var/image/get.md'
        - 'future::constructor': 'api/future/constructor.md'
        - 'future::deconstructor': 'api/future/deconstructor.md'
        - 'future::operator=': 'api/future/assignment_operator.md'
        - 'future::value': 'api/future/value.md'
        - 'future::world': 'api/future/world.md'
        - 'future::operator[]': 'api/future/bracket_operator.md'
        - 'coarray::constructor': 'api/coarray/constructor.md'
        - 'coarray::deconstructor': 'api/coarray/deconstructor.md'
        - 'coarray::operator()': 'api/coarray/parentheses_operator.md'
        - 'coarray::operator[]': 'api/coarray/square_brackets_operator.md'
        - 'coarray::world': 'api/coarray/world.md'
        - 'queue::constructor': 'api/queue/constructor.md'
        - 'queue::deconstructor': 'api/queue/deconstructor.md'
        - 'queue::begin': 'api/queue/begin.md'
        - 'queue::end': 'api/queue/end.md'
        - 'queue::size': 'api/queue/size.md'
        - 'queue::empty': 'api/queue/empty.md'
        - 'queue::world': 'api/queue/world.md'
        - 'queue::sender::send': 'api/queue/sender/send.md'
        - 'partitioning::constructor': 'api/partitioning/constructor.md'
        - 'partitioning::deconstructor': 'api/partitioning/deconstructor.md'
        - 'partitioning::global': 'api/partitioning/global.md'
        - 'partitioning::global_size': 'api/partitioning/global_size.md'
        - 'partitioning::local': 'api/partitioning/local.md'
        - 'partitioning::local_count': 'api/partitioning/local_count.md'
        - 'partitioning::local_size': 'api/partitioning/local_size.md'
        - 'partitioning::owner': 'api/partitioning/owner.md'
        - 'multi_partitioning::constructor': 'api/multi_partitioning/constructor.md'
        - 'multi_partitioning::deconstructor': 'api/multi_partitioning/deconstructor.md'
        - 'multi_partitioning::global': 'api/multi_partitioning/global.md'
        - 'multi_partitioning::grid': 'api/multi_partitioning/grid.md'
        - 'multi_partitioning::local_size': 'api/multi_partitioning/local_size.md'
        - 'multi_partitioning::multi_owner': 'api/multi_partitioning/multi_owner.md'
        - 'multi_partitioning::multi_rank': 'api/multi_partitioning/multi_rank.md'
        - 'multi_partitioning::rank': 'api/multi_partitioning/rank.md'
        - 'cartesian_partitioning::constructor': 'api/cartesian_partitioning/constructor.md'
        - 'cartesian_partitioning::deconstructor': 'api/cartesian_partitioning/deconstructor.md'
        - 'cartesian_partitioning::global': 'api/cartesian_partitioning/global.md'
        - 'cartesian_partitioning::local': 'api/cartesian_partitioning/local.md'
        - 'cartesian_partitioning::local_size': 'api/cartesian_partitioning/local_size.md'
        - 'cartesian_partitioning::owner': 'api/cartesian_partitioning/owner.md'
        - 'rectangular_partitioning::constructor': 'api/rectangular_partitioning/constructor.md'
        - 'rectangular_partitioning::deconstructor': 'api/rectangular_partitioning/deconstructor.md'
        - 'rectangular_partitioning::origin': 'api/rectangular_partitioning/origin.md'
- Backends:
    - MPI: 'backends/mpi.md'
    - thread: 'backends/thread.md'
- BSP model: 'bsp.md'
- Bulk vs BSPlib: 'bulk_vs_bsplib.md'

- Release Notes: 'CHANGELOG.md'

extra:
    palette:
        primary: 'blue grey'
        accent: 'orange'
    social:
        - type: 'github-alt'
          link: 'https://github.com/jwbuurlage'
        - type: 'twitter'
          link: 'https://twitter.com/jwbuurlage'
    logo: 'images/logo.svg'
