p=4096
k=2
file="/scratch-local/bissstud/BigHypergraph/AGATHA_2015/AGATHA_2015.mtx"
eps=0.03
eta=0.03
weights="one"
bisect="multilevel"
metric="lambda_minus_one"
sampling="random"
sample_size=1000
max_cluster_size=20000
lp_max_iter=25
coarsening_nrvertices = 200
coarsening_max_rounds = 128
coarsening_max_edge_size = 10
limit_edge_size="true"
breaking_mode="none"
KLFM_max_passes = 25
KLFM_max_no_gain_moves = 200
KLFM_par_send_moves = 20
