p=4
k=2
file="../test/data/matrices/tbdlinux.mtx"
eps=0.03
eta=0.03
weights="degree"
bisect="multilevel"
metric="lambda_minus_one"
sampling="label_propagation"
sample_size=200
max_cluster_size=30
lp_max_iter=100
coarsening_nrvertices = 300
coarsening_max_rounds = 20
KLFM_max_passes = 100
KLFM_par_send_moves = 20