k=2
eps=0.03
eta=0.03
weights="degree"
bisect="multilevel"
metric="lambda1"
sampling="label propagation"
sample_size=200
max_cluster_size=400
lp_max_iter=4
coarsening_nrvertices = 800
coarsening_max_rounds = 10