p=4
k=2
file="../test/data/matrices/tbdlinux.mtx"
eps=0.03
eta=0.03
weights="degree"
bisect="multilevel"
metric="lambda_minus_one"
sampling="label_propagation"
sample_size=100
max_cluster_size=10
lp_max_iter=25
coarsening_nrvertices = 400
coarsening_max_rounds = 20
KLFM_max_passes = 25
KLFM_max_no_gain_moves = 200
KLFM_par_send_moves = 20