k=2
eps=0.03
eta=0.03
weights="degree"
bisect="multilevel"
metric="lambda_minus_one"
sampling="label_propagation"
sample_size=200
max_cluster_size=400
lp_max_iter=100
coarsening_nrvertices = 800
coarsening_max_rounds = 100
KLFM_max_passes = 100
KLFM_par_send_moves = 100