p=32
k=2
file="../test/data/matrices/atmosmodd/atmosmodd.mtx"
eps=0.03
eta=0.03
weights="degree"
bisect="multilevel"
metric="lambda_minus_one"
sampling="random"
sample_size=25000
max_cluster_size=50
lp_max_iter=25
coarsening_nrvertices = 200
coarsening_max_rounds = 128
KLFM_max_passes = 25
KLFM_max_no_gain_moves = 200
KLFM_par_send_moves = 20
coarsening_max_edge_size = 50
limit_edge_size="false"
breaking_mode="none"
simplify_mode="complete"
