p=64
k=2
file="../test/data/matrices/benchmark_set_a/sat14_9vliw_m_9stages_iq3_C1_bug8.cnf.dual.hgr.mtx"
eps=0.03
eta=0.03
weights="one"
bisect="multilevel"
metric="lambda_minus_one"
sampling="random"
sample_size=8000
max_cluster_size=1000
lp_max_iter=25
coarsening_nrvertices = 100
coarsening_max_rounds = 128
coarsening_max_edge_size = 10
limit_edge_size="true"
breaking_mode="none"
KLFM_max_passes = 25
KLFM_max_no_gain_moves = 200
KLFM_par_send_moves = 20
