file="../test/data/matrices/gemat11/gemat11.mtx"
processors=2
parts=2
eps=0.03
eta=0.03
weights="degree"
bisect=1
sampling=1
metric=1
sample_size=200
max_cluster_size=10
lp_max_iter=100
coarsening_nrvertices=300
coarsening_max_rounds=20
KLFM_max_passes=100
KLFM_max_no_gain_moves=200
KLFM_par_send_moves=20
