file="../test/data/matrices/west0381/west0381.mtx"
processors=4
parts=7
eps=0.03
eta=0.03
weights="degree"
bisect=1
sampling=0
metric=0
sample_size=300
max_cluster_size=30
lp_max_iter=25
coarsening_nrvertices=200
coarsening_max_rounds=20
KLFM_max_passes=25
KLFM_max_no_gain_moves=200
KLFM_par_send_moves=20
