file="../test/data/matrices/atmosmodd/atmosmodd.mtx"
processors=32
parts=2
eps=0.03
eta=0.03
weights="degree"
breaking_mode="none"
limit_edge_size=false
simplify_mode="complete"
bisect=1
sampling=0
metric=1
sample_size=25000
coarsening_max_edge_size=50
max_cluster_size=50
lp_max_iter=25
coarsening_nrvertices=200
coarsening_max_rounds=128
KLFM_max_passes=25
KLFM_max_no_gain_moves=200
KLFM_par_send_moves=20
