file="../test/data/matrices/mhd4800b/mhd4800b.mtx"
processors=2
parts=4
eps=0.03
eta=0.03
weights="degree"
bisect=1
sampling=1
metric=1
sample_size=130
max_cluster_size=20
lp_max_iter=25
coarsening_nrvertices=400
coarsening_max_rounds=20
KLFM_max_passes=25
KLFM_max_no_gain_moves=200
KLFM_par_send_moves=20
