file="../test/data/matrices/gemat11/gemat11.mtx"
processors=4
parts=2
eps=0.03
eta=0.03
weights="degree"
bisect="multilevel"
sampling="label propagation"
metric="lambda1"
sample_size=200
max_cluster_size=400
lp_max_iter=4
coarsening_nrvertices=800
coarsening_max_rounds=10
