file="../test/data/matrices/dolphins/dolphins.mtx"
processors=2
parts=2
eps=0.03
eta=0.03
weights="degree"
bisect=1
sampling=1
metric=1
sample_size=200
max_cluster_size=400
lp_max_iter=4
coarsening_nrvertices=300
coarsening_max_rounds=3
KLFM_max_passes=100
