file="../test/data/matrices/marine1/marine1.mtx"
processors=32
parts=2
eps=0.03
eta=0.03
weights="degree"
bisect=1
sampling=0
metric=1
sample_size=5000
max_cluster_size=50
lp_max_iter=25
coarsening_nrvertices=200
coarsening_max_rounds=128
KLFM_max_passes=25
KLFM_max_no_gain_moves=200
KLFM_par_send_moves=20
