file="../test/data/matrices/gemat11/gemat11.mtx"
processors=1
parts=2
eps=0.03
eta=0.03
weights="degree"
bisect=1
sampling=1
metric=1
sample_size=7
max_cluster_size=5
lp_max_iter=100
coarsening_nrvertices=400
coarsening_max_rounds=20
KLFM_max_passes=1
KLFM_max_no_gain_moves=200
KLFM_par_send_moves=5
