file="../test/data/matrices/west0381/west0381.mtx"
p=4
k=2
eps=0.03
eta=0.03
weights="degree"
bisect="multilevel"
sampling="label propagation"
metric="cutnet"
sample_size=25
max_cluster_size=30
lp_max_iter=4
coarsening_nrvertices=200
coarsening_max_rounds=13
